"""cURL command generator."""

from __future__ import annotations

from oyd_migrator.core.constants import ApiVersions


def generate_curl_commands(
    agent_name: str,
    project_endpoint: str,
    model: str = "gpt-4.1",
) -> str:
    """
    Generate cURL command examples for using a migrated agent.

    Args:
        agent_name: Name of the agent
        project_endpoint: Foundry project endpoint URL
        model: Model deployment name

    Returns:
        Shell script with cURL commands
    """
    return f'''#!/bin/bash
# ============================================================================
# Azure AI Foundry Agent - cURL Examples
#
# Generated by: oyd-foundry-migrator
# Agent: {agent_name}
# Project: {project_endpoint}
# ============================================================================

# Set your access token (get from: az account get-access-token --resource https://ai.azure.com)
export AGENT_TOKEN="<your-access-token>"

# Project endpoint
export PROJECT_ENDPOINT="{project_endpoint}"

# API version
export API_VERSION="{ApiVersions.FOUNDRY_AGENTS}"

# ============================================================================
# 1. Create a Conversation
# ============================================================================

echo "Creating conversation..."

CONVERSATION_RESPONSE=$(curl -s -X POST \\
  "$PROJECT_ENDPOINT/openai/conversations?api-version=2025-11-15-preview" \\
  -H "Authorization: Bearer $AGENT_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{{}}')

CONVERSATION_ID=$(echo $CONVERSATION_RESPONSE | jq -r '.id')
echo "Conversation ID: $CONVERSATION_ID"

# ============================================================================
# 2. Send a Query to the Agent
# ============================================================================

echo ""
echo "Sending query to agent..."

curl -X POST \\
  "$PROJECT_ENDPOINT/openai/responses?api-version=2025-11-15-preview" \\
  -H "Authorization: Bearer $AGENT_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "conversation": "'$CONVERSATION_ID'",
    "input": "What information do you have available?",
    "agent": {{
      "name": "{agent_name}",
      "type": "agent_reference"
    }}
  }}' | jq .

# ============================================================================
# 3. Send a Query with Streaming
# ============================================================================

echo ""
echo "Sending query with streaming..."

curl -X POST \\
  "$PROJECT_ENDPOINT/openai/responses?api-version=2025-11-15-preview" \\
  -H "Authorization: Bearer $AGENT_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "conversation": "'$CONVERSATION_ID'",
    "input": "Can you provide more details?",
    "stream": true,
    "agent": {{
      "name": "{agent_name}",
      "type": "agent_reference"
    }}
  }}'

# ============================================================================
# 4. List Available Agents
# ============================================================================

echo ""
echo "Listing agents..."

curl -s -X GET \\
  "$PROJECT_ENDPOINT/agents?api-version=$API_VERSION" \\
  -H "Authorization: Bearer $AGENT_TOKEN" | jq '.value[] | {{name: .name, model: .model}}'

# ============================================================================
# 5. Get Agent Details
# ============================================================================

echo ""
echo "Getting agent details..."

curl -s -X GET \\
  "$PROJECT_ENDPOINT/agents/{agent_name}?api-version=$API_VERSION" \\
  -H "Authorization: Bearer $AGENT_TOKEN" | jq .

# ============================================================================
# 6. Direct API Call (without pre-created agent)
# ============================================================================

echo ""
echo "Direct API call with inline tool configuration..."

# This example shows how to call the API without a pre-created agent
# by specifying the tools inline

curl -X POST \\
  "$PROJECT_ENDPOINT/openai/responses?api-version=2025-11-15-preview" \\
  -H "Authorization: Bearer $AGENT_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "model": "{model}",
    "input": "What is the main topic covered in your data?",
    "tool_choice": "required",
    "tools": [
      {{
        "type": "azure_ai_search",
        "azure_ai_search": {{
          "indexes": [
            {{
              "project_connection_id": "<your-connection-id>",
              "index_name": "<your-index-name>",
              "query_type": "vector_semantic_hybrid",
              "top_k": 5
            }}
          ]
        }}
      }}
    ]
  }}' | jq .

# ============================================================================
# Helper: Get Access Token
# ============================================================================

# To get an access token using Azure CLI:
# az login
# az account get-access-token --resource https://ai.azure.com --query accessToken -o tsv

# Or using curl with service principal:
# curl -X POST "https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token" \\
#   -d "client_id=<client-id>&scope=https://ai.azure.com/.default&client_secret=<client-secret>&grant_type=client_credentials"
'''
