"""Migration report generator."""

from __future__ import annotations

from datetime import datetime
import json
from typing import Literal

from oyd_migrator.core.config import MigrationState
from oyd_migrator.core.constants import MigrationPath


def generate_report(
    state: MigrationState,
    format: Literal["markdown", "html", "json"] = "markdown",
) -> str:
    """
    Generate a migration report from session state.

    Args:
        state: Migration session state
        format: Output format (markdown, html, json)

    Returns:
        Report content as string
    """
    if format == "json":
        return _generate_json_report(state)
    elif format == "html":
        return _generate_html_report(state)
    else:
        return _generate_markdown_report(state)


def _generate_markdown_report(state: MigrationState) -> str:
    """Generate Markdown format report."""
    path_name = (
        "Azure AI Search Tool"
        if state.migration_options.migration_path == MigrationPath.SEARCH_TOOL
        else "Foundry IQ Knowledge Base"
    )

    # Count test results
    tests_passed = sum(1 for v in state.test_results.values() if v)
    tests_total = len(state.test_results)

    report = f"""# OYD to Foundry Migration Report

**Generated:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC
**Session ID:** {state.session_id}
**Status:** {"Completed" if state.completed else "In Progress"}

---

## Summary

| Metric | Value |
|--------|-------|
| Migration Path | {path_name} |
| Deployments Migrated | {len(state.aoai_configs)} |
| Search Services | {len(state.search_configs)} |
| Connections Created | {len(state.created_connections)} |
| Agents Created | {len(state.created_agents)} |
| Tests Passed | {tests_passed}/{tests_total} |

---

## Source Configuration

### Azure OpenAI Deployments (OYD)

"""

    for config in state.aoai_configs:
        report += f"""#### {config.resource_name}/{config.deployment_name}

- **Resource Group:** {config.resource_group}
- **Endpoint:** {config.endpoint}

"""

    report += """### Connected Search Services

"""

    for config in state.search_configs:
        auth = "Managed Identity" if config.use_managed_identity else "API Key"
        report += f"""- **{config.service_name}**
  - Endpoint: {config.endpoint}
  - Authentication: {auth}

"""

    report += f"""---

## Target Configuration

### Foundry Project

- **Project Name:** {state.foundry_config.project_name if state.foundry_config else "N/A"}
- **Resource Group:** {state.foundry_config.resource_group if state.foundry_config else "N/A"}
- **Endpoint:** {state.foundry_config.project_endpoint if state.foundry_config else "N/A"}
- **Model:** {state.foundry_config.model_deployment if state.foundry_config else "N/A"}

### Migration Options

- **Create New Project:** {"Yes" if state.migration_options.create_new_project else "No"}
- **Preserve Query Type:** {"Yes" if state.migration_options.preserve_query_type else "No"}
- **Migrate System Message:** {"Yes" if state.migration_options.migrate_system_message else "No"}

---

## Created Resources

### Connections

"""

    for conn in state.created_connections:
        report += f"- {conn}\n"

    report += """
### Agents

"""

    for agent in state.created_agents:
        report += f"- {agent}\n"

    if state.test_results:
        report += """
---

## Test Results

| Test | Status |
|------|--------|
"""
        for test_name, passed in state.test_results.items():
            status = "✅ Passed" if passed else "❌ Failed"
            report += f"| {test_name} | {status} |\n"

    report += f"""
---

## Next Steps

1. **Verify Agent Functionality**
   - Test the migrated agents with production queries
   - Compare responses with the original OYD deployment

2. **Update Application Code**
   - Replace AOAI OYD API calls with Foundry Agent Service calls
   - See generated SDK samples for examples

3. **Configure Monitoring**
   - Set up Azure Monitor for the Foundry project
   - Configure alerts for agent errors

4. **Decommission OYD**
   - After successful validation, remove the OYD configuration
   - Consider deleting the AOAI deployment if no longer needed

---

## Resources

- [Foundry Agent Service Documentation](https://learn.microsoft.com/azure/ai-foundry/agents)
- [Azure AI Search Tool](https://learn.microsoft.com/azure/ai-foundry/agents/how-to/tools/ai-search)
- [Foundry IQ Knowledge Base](https://learn.microsoft.com/azure/ai-foundry/agents/how-to/foundry-iq-connect)

---

*Report generated by oyd-foundry-migrator v1.0.0*
"""

    return report


def _generate_html_report(state: MigrationState) -> str:
    """Generate HTML format report."""
    md_report = _generate_markdown_report(state)

    # Basic HTML wrapper - in production you'd use a proper markdown renderer
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OYD Migration Report - {state.session_id}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 2rem;
            line-height: 1.6;
        }}
        h1 {{ color: #0078d4; }}
        h2 {{ color: #106ebe; border-bottom: 1px solid #e1e4e8; padding-bottom: 0.3rem; }}
        table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
        th, td {{ border: 1px solid #e1e4e8; padding: 0.5rem; text-align: left; }}
        th {{ background: #f6f8fa; }}
        code {{ background: #f6f8fa; padding: 0.2rem 0.4rem; border-radius: 3px; }}
        pre {{ background: #f6f8fa; padding: 1rem; overflow-x: auto; }}
        hr {{ border: none; border-top: 1px solid #e1e4e8; margin: 2rem 0; }}
    </style>
</head>
<body>
<pre>{md_report}</pre>
</body>
</html>
"""

    return html


def _generate_json_report(state: MigrationState) -> str:
    """Generate JSON format report."""
    report_data = {
        "metadata": {
            "session_id": state.session_id,
            "generated_at": datetime.utcnow().isoformat(),
            "completed": state.completed,
            "generator": "oyd-foundry-migrator",
            "version": "1.0.0",
        },
        "summary": {
            "migration_path": state.migration_options.migration_path.value,
            "deployments_migrated": len(state.aoai_configs),
            "search_services": len(state.search_configs),
            "connections_created": len(state.created_connections),
            "agents_created": len(state.created_agents),
            "tests_passed": sum(1 for v in state.test_results.values() if v),
            "tests_total": len(state.test_results),
        },
        "source": {
            "aoai_deployments": [
                {
                    "resource_name": c.resource_name,
                    "resource_group": c.resource_group,
                    "deployment_name": c.deployment_name,
                    "endpoint": c.endpoint,
                }
                for c in state.aoai_configs
            ],
            "search_services": [
                {
                    "service_name": c.service_name,
                    "resource_group": c.resource_group,
                    "endpoint": c.endpoint,
                    "use_managed_identity": c.use_managed_identity,
                }
                for c in state.search_configs
            ],
        },
        "target": {
            "project": {
                "name": state.foundry_config.project_name if state.foundry_config else None,
                "resource_group": state.foundry_config.resource_group if state.foundry_config else None,
                "endpoint": state.foundry_config.project_endpoint if state.foundry_config else None,
                "model": state.foundry_config.model_deployment if state.foundry_config else None,
            },
            "options": {
                "create_new_project": state.migration_options.create_new_project,
                "preserve_query_type": state.migration_options.preserve_query_type,
                "migrate_system_message": state.migration_options.migrate_system_message,
            },
        },
        "created_resources": {
            "connections": state.created_connections,
            "agents": state.created_agents,
        },
        "test_results": state.test_results,
    }

    return json.dumps(report_data, indent=2, default=str)
